# frozen_string_literal: true

require 'reline'

module Rvim
end

require_relative 'rvim/version'
require_relative 'rvim/selection'
require_relative 'rvim/text_object'
require_relative 'rvim/operations'
require_relative 'rvim/search'
require_relative 'rvim/registers'
require_relative 'rvim/system_clipboard'
require_relative 'rvim/marks'
require_relative 'rvim/folds'
require_relative 'rvim/diff'
require_relative 'rvim/buffer'
require_relative 'rvim/window'
require_relative 'rvim/tab'
require_relative 'rvim/settings'
require_relative 'rvim/highlights'
require_relative 'rvim/syntax'
require_relative 'rvim/syntax/ruby'
require_relative 'rvim/syntax/markdown'
require_relative 'rvim/syntax/json'
require_relative 'rvim/syntax/shell'
require_relative 'rvim/list_view'
require_relative 'rvim/file_type'
require_relative 'rvim/ftplugins'
require_relative 'rvim/keymap'
require_relative 'rvim/filter'
require_relative 'rvim/completion'
require_relative 'rvim/completion_popup'
require_relative 'rvim/cmdline_completion'
require_relative 'rvim/autocommands'
require_relative 'rvim/modeline'
require_relative 'rvim/match_motion'
require_relative 'rvim/text_motion'
require_relative 'rvim/spell'
require_relative 'rvim/digraphs'
require_relative 'rvim/quickfix'
require_relative 'rvim/undo_file'
require_relative 'rvim/command'
require_relative 'rvim/screen'
require_relative 'rvim/editor'
