# frozen_string_literal: true

module Rvim
  class Settings
    DEFAULTS = {
      hlsearch: true,
      ignorecase: false,
      shiftwidth: 2,
      number: false,
      relativenumber: false,
      smartcase: false,
      syntax: :auto,
      wrap: true,
      tabstop: 8,
      scrolloff: 0,
      cursorline: false,
      ruler: true,
      list: false,
      foldenable: true,
      foldmethod: 'manual',
      foldlevel: 99,
      modeline: true,
      modelines: 5,
      undofile: false,
      wildmenu: true,
      spell: false,
      spelllang: 'en',
      tags: './tags,tags',
      textwidth: 78,
      makeprg: 'make',
      grepprg: 'grep -n $* /dev/null',
      errorformat: '%f:%l:%c:%m,%f:%l:%m',
      expandtab: false,
      listchars: 'tab:> ,trail:·',
      colorcolumn: '',
      cursorcolumn: false,
      fileformat: 'unix',
      statusline: '',
      fileencoding: 'utf-8',
      virtualedit: '',
      mouse: '',
      sidescrolloff: 0,
      splitright: false,
      splitbelow: false,
      showmode: true,
      incsearch: true,
      lazyredraw: false,
      autowrite: false,
      equalalways: true,
      history: 100,
      autoindent: false,
      laststatus: 2,
      nrformats: 'bin,hex',
      smartindent: false,
      startofline: true,
      keywordprg: 'man',
      pumheight: 0,
      linebreak: false,
      backup: false,
      confirm: false,
      title: false,
      titlestring: '',
      showtabline: 1,
      scrolljump: 1,
      backupext: '~',
      backupdir: '.',
      showbreak: '',
      tildeop: false,
      writebackup: true,
      shell: '/bin/sh',
      autoread: false,
      hidden: true,
      undolevels: 1000,
      numberwidth: 4,
      formatprg: '',
      paste: false,
      pastetoggle: '',
      wildignore: '',
      endofline: true,
      infercase: false,
      equalprg: '',
      breakindent: false,
      fixendofline: true,
      shellcmdflag: '-c',
      grepformat: '%f:%l:%c:%m,%f:%l:%m',
      belloff: 'all',
      signcolumn: 'auto',
      updatetime: 4000,
      shortmess: 'filnxtToOS',
      clipboard: '',
      background: 'dark',
      switchbuf: 'uselast',
      magic: true,
      eadirection: 'both',
      completeopt: 'menu',
      timeout: true,
      timeoutlen: 1000,
      ttimeoutlen: -1,
      isfname: '@,48-57,/,.,-,_,+,,,#,$,%,~,=',
      isident: '@,48-57,_,192-255',
      wrapscan: true,
      cmdheight: 1,
      report: 2,
      iskeyword: '@,48-57,_,192-255',
      matchpairs: '(:),{:},[:]',
      formatoptions: 'tcq',
      comments: 's1:/*,mb:*,ex:*/,://,b:#,:%,:XCOMM,n:>,fb:-',
      commentstring: '/*%s*/',
      path: '.,,',
      winminheight: 1,
      winheight: 1,
      winwidth: 20,
      winminwidth: 1,
      synmaxcol: 3000,
      redrawtime: 2000,
    }.freeze

    ALIASES = {
      'hls' => :hlsearch,
      'ic' => :ignorecase,
      'nu' => :number,
      'rnu' => :relativenumber,
      'scs' => :smartcase,
      'sw' => :shiftwidth,
      'syn' => :syntax,
      'ts' => :tabstop,
      'so' => :scrolloff,
      'cul' => :cursorline,
      'ru' => :ruler,
      'fen' => :foldenable,
      'fdm' => :foldmethod,
      'fdl' => :foldlevel,
      'ml' => :modeline,
      'mls' => :modelines,
      'udf' => :undofile,
      'wmnu' => :wildmenu,
      'tw' => :textwidth,
      'mp' => :makeprg,
      'gp' => :grepprg,
      'efm' => :errorformat,
      'et' => :expandtab,
      'lcs' => :listchars,
      'cc' => :colorcolumn,
      'cuc' => :cursorcolumn,
      'ff' => :fileformat,
      'stl' => :statusline,
      'fenc' => :fileencoding,
      've' => :virtualedit,
      'siso' => :sidescrolloff,
      'spr' => :splitright,
      'sb' => :splitbelow,
      'smd' => :showmode,
      'is' => :incsearch,
      'lz' => :lazyredraw,
      'aw' => :autowrite,
      'ea' => :equalalways,
      'hi' => :history,
      'ai' => :autoindent,
      'ls' => :laststatus,
      'nf' => :nrformats,
      'si' => :smartindent,
      'sol' => :startofline,
      'kp' => :keywordprg,
      'ph' => :pumheight,
      'lbr' => :linebreak,
      'bk' => :backup,
      'cf' => :confirm,
      'tl' => :title,
      'stl_str' => :titlestring,
      'stal' => :showtabline,
      'sj' => :scrolljump,
      'bex' => :backupext,
      'bdir' => :backupdir,
      'sbr' => :showbreak,
      'top' => :tildeop,
      'wb' => :writebackup,
      'sh' => :shell,
      'ar' => :autoread,
      'hid' => :hidden,
      'ul' => :undolevels,
      'nuw' => :numberwidth,
      'fp' => :formatprg,
      'ps' => :paste,
      'pt' => :pastetoggle,
      'wig' => :wildignore,
      'eol' => :endofline,
      'inf' => :infercase,
      'ep' => :equalprg,
      'bri' => :breakindent,
      'fixeol' => :fixendofline,
      'shcf' => :shellcmdflag,
      'gfm' => :grepformat,
      'bo' => :belloff,
      'scl' => :signcolumn,
      'ut' => :updatetime,
      'shm' => :shortmess,
      'cb' => :clipboard,
      'bg' => :background,
      'swb' => :switchbuf,
      'ead' => :eadirection,
      'cot' => :completeopt,
      'to' => :timeout,
      'tm' => :timeoutlen,
      'isf' => :isfname,
      'isi' => :isident,
      'ws' => :wrapscan,
      'ch' => :cmdheight,
      'isk' => :iskeyword,
      'mps' => :matchpairs,
      'fo' => :formatoptions,
      'com' => :comments,
      'cms' => :commentstring,
      'pa' => :path,
      'wmh' => :winminheight,
      'wh' => :winheight,
      'wiw' => :winwidth,
      'wmw' => :winminwidth,
      'smc' => :synmaxcol,
      'rdt' => :redrawtime,
    }.freeze

    KNOWN = (DEFAULTS.keys + ALIASES.values).uniq.freeze

    def initialize
      @options = DEFAULTS.dup
      @editor = nil
    end

    attr_accessor :editor

    def get(name, buffer: :current)
      key = normalize(name)
      buf = buffer == :current ? @editor&.current_buffer : buffer
      if buf && buf.respond_to?(:local_settings) && buf.local_settings.key?(key)
        buf.local_settings[key]
      else
        @options[key]
      end
    end

    def set(name, value, buffer: nil)
      key = normalize(name)
      if buffer
        buffer.local_settings[key] = value
      else
        @options[key] = value
      end
      key
    end

    def known?(name)
      KNOWN.include?(normalize(name))
    end

    def normalize(name)
      sym = name.to_s
      ALIASES[sym] || sym.to_sym
    end
  end
end
